Add google map field to demo
Laravel-Backpack/demo pull request #434
Opened 2022-10-14 10:03 UTC by pxpm

added two google map field examples, one in `Owner` and other in `Passport` to show both saving options (same column json or multiple columns).

2022-10-14 10:10 UTC, EGYWEB-Mohamed commented
Good Job @pxpm 🎉🎉

2022-11-28 12:49 UTC, jorgetwgroup commented
Hello @pxpm 

Maps works great! i just have a fail with "Get my location button" (see screeshont)

![screenshot-backpack test-2022 11 28-09_46_49](https://user-images.githubusercontent.com/44643608/204281633-c90d27e3-218b-4037-82e4-e29f079f5ecc.png)

![Screenshot 2022-11-28 at 09 46 09](https://user-images.githubusercontent.com/44643608/204281658-6a5ffabd-a3a3-4a05-8818-1d6f9866f293.png)

But maps load normal and i can move pin and show me new location.

![screenshot-backpack test-2022 11 28-09_45_38](https://user-images.githubusercontent.com/44643608/204281770-fbf3d853-15b4-4b3f-bb24-609a41169b1d.png)

Let me know if something is wrong with my config, i set my api key in "GOOGLE_PLACES_KEY".

Cheers.

2022-11-28 13:36 UTC, pxpm commented
@jorgetwgroup you browser location is not available locally without https 👍 

@tabacitu can you create a subdomain for this branch online so that we fully test the location services ? Something like https://demomaps.backpackforlaravel.com ? 

Going through the route of getting https locally is a pain, trust me, I've been there more than once!

Cheers

2022-12-27 13:58 UTC, tabacitu commented
Hmm... I can confirm they _work_ in both places but... I wouldn't agree that they _make sense_ in those CRUDs @pxpm . Quite the contrary - I think we had a few "clean" forms there with `Passport` and `Owner`, and adding this example there... bloats them up. I especially dislike how the Owner form looks now, with all that white space, not pretty at all:

![](https://user-images.githubusercontent.com/44643608/204281633-c90d27e3-218b-4037-82e4-e29f079f5ecc.png)

Let's please:
- [ ] move the `google_map` field to the Monster form, at the bottom of the "Time and space" tab; that's where we have ALL our field types so... why wouldn't it be there?! plus, then it will be picked up by the other related CRUDs so we can easily test it's working with CrudField JS API, etc;
- [ ] if we need to show a different functionality for it (eg. store `lat` and `long` in different columns) we should also add it to another "bloated" CRUD, for example... Cave? Yeah, I think Cave is a good one, it only has two fields so it won't be messy at the end of that; plus, it makes more sense for a Cave to have `lat` and `long` than a Passport or Owner, right?

2022-12-27 18:09 UTC, pxpm commented
Done both things, moved one of the map fields to monster that stores in a single fake column, and another one to cave that stores the inputs separatelly. 

👍

2022-12-27 18:12 UTC, tabacitu requested changes

2022-12-27 18:12 UTC, tabacitu commented on app/Http/Controllers/Admin/PetShop/OwnerCrudController.php
> +        CRUD::field('name')->wrapper(['class' => 'form-group col-md-6']);
No need for this field to be smaller now that it doesn't have the google map. Also... `->size(6)` man... does the same thing... fluent syntax FTW! You're old-school, I know, I know 😅

```suggestion
        CRUD::field('name');
```

2022-12-27 18:12 UTC, tabacitu commented on app/Http/Controllers/Admin/PetShop/PassportCrudController.php
> +        CRUD::field('pet')->wrapper(['class' => 'form-group col-md-6']);
```suggestion
        CRUD::field('pet');
```

2022-12-27 18:16 UTC, tabacitu requested changes

2022-12-27 18:16 UTC, tabacitu commented on app/Models/PetShop/Owner.php
> +        'name', 'address',
```suggestion
        'name',
```

2022-12-27 18:16 UTC, tabacitu commented on app/Models/PetShop/Passport.php
> +    }
```suggestion

```

2022-12-27 18:16 UTC, tabacitu commented on database/migrations/2022_01_17_083405_create_owners_table.php
> +            $table->text('address')->nullable();
```suggestion
```

2022-12-27 18:16 UTC, tabacitu commented on app/Models/PetShop/Passport.php
> +        'location',
```suggestion
```

2022-12-27 18:16 UTC, tabacitu commented on app/Models/PetShop/Passport.php
> +use Illuminate\Database\Eloquent\Casts\Attribute;
```suggestion
```

2022-12-27 18:16 UTC, tabacitu commented on app/Models/PetShop/Passport.php
> +use Illuminate\Database\Eloquent\Casts\Attribute;
```suggestion
```

2022-12-27 18:24 UTC, tabacitu approved these changes

2022-12-27 19:01 UTC, merged